export const ARTISANS = [
  {
    id: 1,
    profilePic: require('../../assets/users/Rectangle.png'),
    name: 'Ayo the barber',
    slug: 'affordable haircut from the comfort of your home',
    pricing: '$100/hr',
    distance: '500m Away',
    isSaved: false,
    ratings: 5,
  },
  {
    id: 2,
    profilePic: require('../../assets/users/Rectangle75u.png'),
    name: 'Jane Fashion Home',
    slug: 'deliver the best fashion service and styles...',
    pricing: '$100/hr',
    distance: '500m Away',
    isSaved: false,
    ratings: 4,
  },
  {
    id: 3,
    profilePic: require('../../assets/users/Rectangle75.png'),
    name: 'Ayo the barber',
    slug: 'affordable haircut from the comfort of your home',
    pricing: '$100/hr',
    distance: '500m Away',
    isSaved: false,
    ratings: 5,
  },
  {
    id: 4,
    profilePic: require('../../assets/users/Rectangle.png'),
    name: 'Ayo the barber',
    slug: 'affordable haircut from the comfort of your home',
    pricing: '$100/hr',
    distance: '500m Away',
    isSaved: false,
    ratings: 5,
  },
  {
    id: 5,
    profilePic: require('../../assets/users/Rectangle.png'),
    name: 'Ayo the barber',
    slug: 'affordable haircut from the comfort of your home',
    pricing: '$100/hr',
    distance: '500m Away',
    isSaved: false,
    ratings: 5,
  },
  {
    id: 6,
    profilePic: require('../../assets/users/Rectangle75u.png'),
    name: 'Ayo the barber',
    slug: 'affordable haircut from the comfort of your home',
    pricing: '$100/hr',
    distance: '500m Away',
    isSaved: false,
    ratings: 5,
  },
  {
    id: 7,
    profilePic: require('../../assets/users/Rectangle75.png'),
    name: 'Ayo the barber',
    slug: 'affordable haircut from the comfort of your home',
    pricing: '$100/hr',
    distance: '500m Away',
    isSaved: false,
    ratings: 5,
  },
  {
    id: 8,
    profilePic: require('../../assets/users/Rectangle.png'),
    name: 'Ayo the barber',
    slug: 'affordable haircut from the comfort of your home',
    pricing: '$100/hr',
    distance: '500m Away',
    isSaved: false,
    ratings: 5,
  },
]